neo4j-standalone:
  neo4j: 
    resources: {}
  volumes:
    data: 
      mode: "defaultStorageClass"
  podSpec:
    serviceAccountName: stellio
  config:
    dbms.allow_upgrade: "true"
    dbms.default_database: "stellio"
    dbms.security.procedures.unrestricted: "apoc.*"
    dbms.security.procedures.allowlist: "apoc.*"
    dbms.ssl.policy.bolt.client_auth: "NONE"
    dbms.ssl.policy.https.client_auth: "NONE"
    dbms.security.auth_enabled: "false"