source: https://github.com/wistefan/broker-federation
release: broker-federation
destination_namespace: &destination broker-federation
branch: &branch main

applications:
  - name: certificates
    enabled: true
    source_path: brokers/ssl
    source_ref: *branch
    destination: *destination

  - name: orion-ld
    enabled: true
    source_path: brokers/orion-ld/orion-ld
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml

  - name: orion-ld-mongodb
    enabled: true
    source_path: brokers/orion-ld/mongodb
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml

  - name: scorpio
    enabled: true
    source_path: brokers/scorpio/scorpio
    source_ref: *branch
    destination: *destination

  - name: scorpio-kafka
    enabled: true
    source_path: brokers/scorpio/kafka
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml

  - name: scorpio-postgres
    enabled: true
    source_path: brokers/scorpio/postgres
    source_ref: *branch
    destination: *destination