source: https://github.com/wistefan/broker-federation
release: broker-federation
destination_namespace: &destination broker-federation
branch: &branch main

applications:
  # shared services

  - name: certificates
    broker: shared
    enabled: true
    source_path: brokers/ssl
    source_ref: *branch
    destination: *destination

  # orion-ld services

  - name: orion-ld
    broker: orion-ld
    enabled: true
    source_path: brokers/orion-ld/orion-ld
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml

  - name: orion-ld-mongodb
    broker: orion-ld
    enabled: true
    source_path: brokers/orion-ld/mongodb
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml

  # scorpio services

  - name: scorpio
    broker: scorpio
    enabled: true
    source_path: brokers/scorpio/scorpio
    source_ref: *branch
    destination: *destination

  - name: scorpio-service-account
    broker: scorpio
    enabled: true
    source_path: brokers/scorpio/service-account
    source_ref: *branch
    destination: *destination

  - name: scorpio-kafka
    broker: scorpio
    enabled: true
    source_path: brokers/scorpio/kafka
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml

  - name: scorpio-postgres
    broker: scorpio
    enabled: true
    source_path: brokers/scorpio/postgres
    source_ref: *branch
    destination: *destination

  - name: scorpio-map
    broker: scorpio
    enabled: true
    source_path: brokers/scorpio/map
    source_ref: *branch
    destination: *destination

  # stellio services

  - name: stellio-kafka
    broker: stellio
    enabled: true
    source_path: brokers/stellio/kafka
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml

  - name: stellio-neo4j
    broker: stellio
    enabled: true
    source_path: brokers/stellio/neo4j
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml

  - name: stellio-timescale
    broker: stellio
    enabled: true
    source_path: brokers/stellio/timescale
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml

  - name: stellio-service-account
    broker: stellio
    enabled: true
    source_path: brokers/stellio/service-account
    source_ref: *branch
    destination: *destination

  - name: stellio
    broker: stellio
    enabled: true
    source_path: brokers/stellio/stellio
    source_ref: *branch
    destination: *destination