apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: stellio
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
  - delete
- apiGroups:
    - ''
  resources:
  - endpoints
  - endpoints/restricted
  verbs:
  - create
  - get
  - patch
  - update
  - list
  - watch
  - delete

- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch