apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stellio-scc-anyuid
subjects:
  - kind: ServiceAccount
    name: stellio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: stellio