apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-init-scripts
data:
  shell_test.sh: |+
    #!/bin/sh
    psql <<- EOSQL
      CREATE USER search_db WITH PASSWORD 'postgres-password';
      CREATE USER subscription_db WITH PASSWORD 'postgres-password';
      CREATE database search_db;
      CREATE database subscription_db;
    EOSQL
    psql -d subscription_db <<- EOSQL
      CREATE EXTENSION postgis;
    EOSQL