apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-init-scripts
data:
  plain.sql: |
    CREATE USER search_db WITH PASSWORD 'postgres-password';
    CREATE USER subscription_db WITH PASSWORD 'postgres-password';
    CREATE database search_db;
    CREATE database subscription_db;
    \c subscription_db;
    CREATE EXTENSION postgis;