apiVersion: v2
name: timescale
description: Chart holder for argo-cd

type: application
version: 0.1.0
appVersion: "1.7.4"

dependencies:
- name: timescaledb-single
  version: v0.7.1
  repository: https://charts.timescale.com