timescaledb-single:
  image:
    repository: stellio/stellio-timescale-postgis
    tag: 2.3.0-pg13
  persistentVolumes:
    data:
      size: 2Gi
  rbac:
    create: true
  serviceAccount: 
    create: false
    name: stellio
  postInit: 
    - configMap:
        name: custom-init-scripts
        optional: false
  secrets:
    credentials:
      PATRONI_SUPERUSER_PASSWORD: "postgres-password"
      PATRONI_REPLICATION_PASSWORD: "postgres-password"
      PATRONI_admin_PASSWORD: "postgres-password"
  replicaCount: 1