timescaledb-single:
  image:
    repository: timescale/timescaledb-ha
    tag: pg13-ts2.3-latest
  persistentVolumes:
    data:
      size: 10Gi
  resources: {}
  rbac:
    create: true
  serviceAccount: 
    create: false
    name: stellio