timescaledb-single:
  image:
    repository: timescale/timescaledb-ha
    tag: pg13-ts2.3-latest
  persistentVolumes:
    data:
      size: 2Gi
  rbac:
    create: true
  serviceAccount: 
    create: false
    name: stellio
  patroni: 
    postgresql: 
      pg_hba:
        - local     all             postgres                              peer
        - local     all             all                                   md5
        - hostnossl all,replication all                all                md5
        - hostssl   all             all                127.0.0.1/32       md5
        - hostssl   all             all                ::1/128            md5
        - hostssl   replication     standby            all                md5
        - hostssl   all             all                all                md5
  postInit: 
    - configMap:
        name: custom-init-scripts
        optional: false
  secrets:
    credentials:
      PATRONI_SUPERUSER_PASSWORD: "postgres-password"
      PATRONI_REPLICATION_PASSWORD: "postgres-password"
      PATRONI_admin_PASSWORD: "postgres-password"
  replicaCount: 1