timescaledb-single:
  image:
    repository: timescale/timescaledb-ha
    tag: pg13-ts2.3-latest
  persistentVolumes:
    data:
      size: 2Gi
  rbac:
    create: true
  serviceAccount: 
    create: false
    name: stellio
  postInit: 
    - configMap:
        name: custom-init-scripts
        optional: false
  secrets:
    credentials:
        PATRONI_SUPERUSER_PASSWORD: "postgres-password"
        PATRONI_REPLICATION_PASSWORD: "postgres-password"
        PATRONI_admin_PASSWORD: "postgres-password"
