kafka:
  fullnameOverride: stellio-kafka
  serviceAccount:
    create: false
    name: stellio
  persistence:
    enabled: false
  zookeeper:
    persistence:
      enabled: false
    serviceAccount:
      create: false
      name: stellio